version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/php.ini
      - ~/.bash_history:/root/.bash_history
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    image: mysql:5.7
    container_name: ${APP_NAME}-dbhost
    restart: unless-stopped
    ports:
      - ${DEFAULT_DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${APP_NAME}-db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - ${DEFAULT_APP_PORT}:80
    volumes:
      - ./app:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - app-network

  redis:
    container_name: ${APP_NAME}-redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
